# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfs.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\x12\x03\x64\x66s\"\x07\n\x05\x45mpty\"/\n\nPutRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x1e\n\x0bPutResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\nGetRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1e\n\x0bGetResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\"\n\x11ListFilesResponse\x12\r\n\x05\x66iles\x18\x01 \x03(\t\"+\n\x16\x43hangeDirectoryRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\"$\n\x11\x44irectoryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x14MakeDirectoryRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\"+\n\x16RemoveDirectoryRequest\x12\x11\n\tdirectory\x18\x01 \x01(\t\"%\n\x11RemoveFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1f\n\x0c\x46ileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"3\n\x11StoreBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"%\n\x12StoreBlockResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0fGetBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\" \n\x10GetBlockResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x9c\x03\n\x08NameNode\x12(\n\x03Put\x12\x0f.dfs.PutRequest\x1a\x10.dfs.PutResponse\x12(\n\x03Get\x12\x0f.dfs.GetRequest\x1a\x10.dfs.GetResponse\x12/\n\tListFiles\x12\n.dfs.Empty\x1a\x16.dfs.ListFilesResponse\x12\x46\n\x0f\x43hangeDirectory\x12\x1b.dfs.ChangeDirectoryRequest\x1a\x16.dfs.DirectoryResponse\x12\x42\n\rMakeDirectory\x12\x19.dfs.MakeDirectoryRequest\x1a\x16.dfs.DirectoryResponse\x12\x46\n\x0fRemoveDirectory\x12\x1b.dfs.RemoveDirectoryRequest\x1a\x16.dfs.DirectoryResponse\x12\x37\n\nRemoveFile\x12\x16.dfs.RemoveFileRequest\x1a\x11.dfs.FileResponse2\x82\x01\n\x08\x44\x61taNode\x12=\n\nStoreBlock\x12\x16.dfs.StoreBlockRequest\x1a\x17.dfs.StoreBlockResponse\x12\x37\n\x08GetBlock\x12\x14.dfs.GetBlockRequest\x1a\x15.dfs.GetBlockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_PUTREQUEST']._serialized_start=27
  _globals['_PUTREQUEST']._serialized_end=74
  _globals['_PUTRESPONSE']._serialized_start=76
  _globals['_PUTRESPONSE']._serialized_end=106
  _globals['_GETREQUEST']._serialized_start=108
  _globals['_GETREQUEST']._serialized_end=138
  _globals['_GETRESPONSE']._serialized_start=140
  _globals['_GETRESPONSE']._serialized_end=170
  _globals['_LISTFILESRESPONSE']._serialized_start=172
  _globals['_LISTFILESRESPONSE']._serialized_end=206
  _globals['_CHANGEDIRECTORYREQUEST']._serialized_start=208
  _globals['_CHANGEDIRECTORYREQUEST']._serialized_end=251
  _globals['_DIRECTORYRESPONSE']._serialized_start=253
  _globals['_DIRECTORYRESPONSE']._serialized_end=289
  _globals['_MAKEDIRECTORYREQUEST']._serialized_start=291
  _globals['_MAKEDIRECTORYREQUEST']._serialized_end=332
  _globals['_REMOVEDIRECTORYREQUEST']._serialized_start=334
  _globals['_REMOVEDIRECTORYREQUEST']._serialized_end=377
  _globals['_REMOVEFILEREQUEST']._serialized_start=379
  _globals['_REMOVEFILEREQUEST']._serialized_end=416
  _globals['_FILERESPONSE']._serialized_start=418
  _globals['_FILERESPONSE']._serialized_end=449
  _globals['_STOREBLOCKREQUEST']._serialized_start=451
  _globals['_STOREBLOCKREQUEST']._serialized_end=502
  _globals['_STOREBLOCKRESPONSE']._serialized_start=504
  _globals['_STOREBLOCKRESPONSE']._serialized_end=541
  _globals['_GETBLOCKREQUEST']._serialized_start=543
  _globals['_GETBLOCKREQUEST']._serialized_end=578
  _globals['_GETBLOCKRESPONSE']._serialized_start=580
  _globals['_GETBLOCKRESPONSE']._serialized_end=612
  _globals['_NAMENODE']._serialized_start=615
  _globals['_NAMENODE']._serialized_end=1027
  _globals['_DATANODE']._serialized_start=1030
  _globals['_DATANODE']._serialized_end=1160
# @@protoc_insertion_point(module_scope)
